name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run one-line script
        run: echo "Hello, world!"
        continue-on-error: true
      - name: Run multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
        continue-on-error: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-artifact
      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-relay.sendinblue.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: konavvart@gmail.com
          to: kvvaravitej@gmail.com
          subject: ${{ github.repository }} test results
          body: |
            Test results for ${{ github.repository }}:

            Job build:
            Status: ${{ job.status }}
            Conclusion: ${{ job.conclusion }}

            Steps:
            - Checkout code: ${{ success_or_failure_expression: job.steps['Checkout code'].outcome, default: 'Failed' }}
            - Run one-line script: ${{ success_or_failure_expression: job.steps['Run one-line script'].outcome, default: 'Failed' }}
            - Run multi-line script: ${{ success_or_failure_expression: job.steps['Run multi-line script'].outcome, default: 'Failed' }}
            - Upload artifact: ${{ success_or_failure_expression: job.steps['Upload artifact'].outcome, default: 'Failed' }}            
