name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Run one-line script
        run: echo "Hello, world!"
        continue-on-error: true
      - name: Run multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
        continue-on-error: true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-artifact

  send_notification:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-relay.sendinblue.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: konavvart@gmail.com
          to: kvvaravitej@gmail.com
          subject: ${{ github.repository }} test results
          body: |
            Test results for ${{ github.repository }}:

            Job build:
            Status: ${{ job.status }}
            Conclusion: ${{ job.conclusion }}

            Steps:
            - Checkout code: ${{ job.build.steps['Checkout code'].outcome }}
            - Run one-line script: ${{ job.steps['Run one-line script'].outcome }}
            - Run multi-line script: ${{ job.steps['Run multi-line script'].outcome }}
            - Upload artifact: ${{ job.steps['Upload artifact'].outcome }}

            # Job test2:
            # Status: ${{ job.status_2 }}
            # Conclusion: ${{ job.conclusion_2 }}'
